version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build
            
jobs:
  build:
   working_directory: ~/ExampleApplication
   docker:
     - image: circleci/node:10.16.3
   steps:
     - checkout
     - setup_remote_docker
     - run:
         name: update-npm
         command: 'sudo npm install -g npm@5'
     - restore_cache:
         key: dependency-cache-{{ checksum "package-lock.json" }}
     - run:
         name: install-npm-wee
         command: npm install
     - save_cache:
         key: dependency-cache-{{ checksum "package-lock.json" }}
         paths:
           - ./node_modules
     - run:
          name: docker-login
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
     - run:
          name: build-docker-image
          command: docker build -t $IMAGE_NAME:latest .
     - run:
          name: publish-docker-image
          command: docker push $IMAGE_NAME
     - run:
          name: set-environment-variables
          command: echo $server > server.crt && echo $privatekey > privatekey.pem
     - run:
          name: build-docker-image-for-integration-environment
          command: docker create -p 8443:8443 --name week3Lab1 $IMAGE_NAME
     - run:
          name: copy-server-cert-and-privatekey-accross
          command: docker cp ./privatekey.pem week3Lab:/privatekey.pem; docker cp ./server.crt week3Lab1:/server.crt
     - run:
          name: start-docker-container
          command: docker start week3Lab1
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export server=\"$server\"; export IMAGE_NAME=\"$IMAGE_NAME\"; export privatekey=\"$privatekey\"; rm -rf week3Lab/;git clone https://github.com/DanielJMorrissey/week3Lab.git; source week3Lab/deploy.sh"